import Form$1 from './Form.js';
import './style/css.js';
import '@babel/runtime/helpers/toConsumableArray';
import '@babel/runtime/helpers/slicedToArray';
import '@babel/runtime/helpers/defineProperty';
import '../_chunks/dep-C52Ear6B.js';
import '@babel/runtime/helpers/typeof';
import 'classnames';
import '../_chunks/dep-CaeblIEM.js';
import '../config-provider/ConfigContext.js';
import '../_chunks/dep-U1T8CQY9.js';
import '../_chunks/dep-Bdljkd5o.js';
import 'hoist-non-react-statics';
import './hooks/useInstance.js';
import '@babel/runtime/helpers/objectWithoutProperties';
import '@babel/runtime/helpers/asyncToGenerator';
import '@babel/runtime/regenerator';
import 'lodash-es';
import './utils/index.js';
import '../_chunks/dep-CcL4GSfv.js';
import '@babel/runtime/helpers/createClass';
import '@babel/runtime/helpers/classCallCheck';
import './FormContext.js';
import '../_chunks/dep-m5bu896E.js';
import 'tdesign-icons-react';
import '../_chunks/dep-e4v9VeEm.js';
import '../_chunks/dep-Dp0dxPtr.js';
import '../_chunks/dep-BpYapwIO.js';
import '../_chunks/dep-DWZDJ_hQ.js';
import 'validator/lib/isDate';
import 'validator/lib/isEmail';
import 'validator/lib/isURL';
import '../_chunks/dep-C4qiDhnV.js';
import '../common/Check.js';
import '../_chunks/dep-Dqh5DYAh.js';
import '../tag-input/TagInput.js';
import 'lucide-react';
import '../_chunks/dep-CCk9KX71.js';
import '../_chunks/dep-6TeJvJOF.js';
import '../tag-input/hooks/useTagList.js';
import '../tag/index.js';
import '../tag/Tag.js';
import 'tinycolor2';
import '../hooks/useDragSorter.js';
import './FormList.js';

var Form = Form$1;

export { Form, Form as default };
//# sourceMappingURL=index.js.map
