import Dialog$1 from './Dialog.js';
import { D as DialogCard$1 } from '../_chunks/dep-CDPvR3ml.js';
import { DialogPlugin as DialogPlugin$1 } from './plugin.js';
import './style/css.js';
import '../_chunks/dep-mO86zOh3.js';
import '../_chunks/dep-Cwish4GD.js';
import '../_chunks/dep-D-UKOauR.js';
import '../_chunks/dep-CzLhKWCf.js';
import '../_chunks/dep-DcgYxvIK.js';
import 'react';
import '../_chunks/dep-DTNqJ2we.js';
import '../_chunks/dep-0Agal8xo.js';
import '../_chunks/dep-DFvx9dpR.js';
import 'react-dom';
import '../_chunks/dep-Cro9u0Fl.js';
import '../_chunks/dep-uPo9oRq0.js';
import '../common/Portal.js';
import '../_chunks/dep-0EpSXuwN.js';
import '../_chunks/dep-u1x3x6MJ.js';
import '../config-provider/ConfigContext.js';
import '../_chunks/dep-5jl2j2BI.js';
import '../_chunks/dep-CgyDw_YI.js';
import '../_chunks/dep-LgDsOUkE.js';
import '../button/index.js';
import '../button/Button.js';
import '../loading/index.js';
import '../loading/Loading.js';
import '../loading/Gradient.js';
import '../_chunks/dep-CCwJVofP.js';
import '../_chunks/dep-BlRTpQ02.js';
import '../_chunks/dep-D9QqIBS0.js';
import '../loading/style/css.js';
import '../_chunks/dep-CVM4W9uS.js';
import '../button/style/css.js';
import '../_chunks/dep-BIZNqCbw.js';
import '../_chunks/dep-CEvoJEXM.js';
import '../common/PluginContainer.js';
import '../config-provider/index.js';
import '../config-provider/ConfigProvider.js';

var Dialog = Dialog$1;
var DialogCard = DialogCard$1;
var dialog = DialogPlugin$1;
var DialogPlugin = DialogPlugin$1;

export { Dialog, DialogCard, DialogPlugin, Dialog as default, dialog };
//# sourceMappingURL=index.js.map
