import Dialog$1 from './Dialog.js';
import { D as DialogCard$1 } from '../_chunks/dep-Bctoac_0.js';
import { DialogPlugin as DialogPlugin$1 } from './plugin.js';
import './style/css.js';
import '../_chunks/dep-Cwish4GD.js';
import '../_chunks/dep-D-UKOauR.js';
import '../_chunks/dep-CzLhKWCf.js';
import '../_chunks/dep-DN7d1SzH.js';
import 'react';
import 'react-transition-group';
import 'classnames';
import 'lodash-es';
import '../common/Portal.js';
import 'react-dom';
import '../_chunks/dep-DRwijJcv.js';
import '../_chunks/dep-u7AyxuYF.js';
import '../_chunks/dep-zVwpnryi.js';
import 'dayjs';
import '../_chunks/dep-BRbJGDI9.js';
import '../_chunks/dep-TZtijX-L.js';
import '../_chunks/dep-DGvfel3I.js';
import '../_chunks/dep-BbeHB7S3.js';
import '../_chunks/dep-CgyDw_YI.js';
import '@tendaui/icons';
import '../button/index.js';
import '../button/Button.js';
import '../loading/index.js';
import '../loading/Loading.js';
import '../loading/Gradient.js';
import '../_chunks/dep-DHWwZ2Nj.js';
import '../_chunks/dep-PPA-yoAy.js';
import '../_chunks/dep-DbVHGoUC.js';
import '../loading/style/css.js';
import '../_chunks/dep-D6YxJv-F.js';
import '../button/style/css.js';
import '../_chunks/dep-sSDUpJwy.js';
import '../_chunks/dep-BGP3l2nd.js';
import '../config-provider/index.js';
import '../config-provider/ConfigProvider.js';
import '../_chunks/dep-DUWadCCb.js';
import '../common/PluginContainer.js';

var Dialog = Dialog$1;
var DialogCard = DialogCard$1;
var dialog = DialogPlugin$1;
var DialogPlugin = DialogPlugin$1;

export { Dialog, DialogCard, DialogPlugin, Dialog as default, dialog };
//# sourceMappingURL=index.js.map
