import Dialog$1 from './Dialog.js';
import { D as DialogCard$1 } from '../_chunks/dep-CdS-KBHO.js';
import { DialogPlugin as DialogPlugin$1 } from './plugin.js';
import './style/css.js';
import '@babel/runtime/helpers/defineProperty';
import '@babel/runtime/helpers/slicedToArray';
import '@babel/runtime/helpers/objectWithoutProperties';
import '../_chunks/dep-C52Ear6B.js';
import '@babel/runtime/helpers/typeof';
import 'react-transition-group';
import 'classnames';
import 'lodash-es';
import '../common/Portal.js';
import '../_chunks/dep-DU45RdGB.js';
import '../_chunks/dep-6TeJvJOF.js';
import '../_chunks/dep-CaeblIEM.js';
import '../config-provider/ConfigContext.js';
import '../_chunks/dep-DJQi-lRj.js';
import '../_chunks/dep-e4v9VeEm.js';
import '@babel/runtime/helpers/toConsumableArray';
import 'tdesign-icons-react';
import '../_chunks/dep-CWE5nGYy.js';
import '../loading/index.js';
import '../loading/Loading.js';
import '../loading/Gradient.js';
import '../_chunks/dep-C4qiDhnV.js';
import '../_chunks/dep-py6q5XhT.js';
import '../_chunks/dep-2sN3YgeE.js';
import '../_chunks/dep-DWZDJ_hQ.js';
import '../_chunks/dep-Dp0dxPtr.js';
import '../_chunks/dep-B6ztXA2I.js';
import '@babel/runtime/helpers/asyncToGenerator';
import '@babel/runtime/regenerator';
import '../common/PluginContainer.js';
import '../config-provider/index.js';
import '../config-provider/ConfigProvider.js';

var Dialog = Dialog$1;
var DialogCard = DialogCard$1;
var dialog = DialogPlugin$1;
var DialogPlugin = DialogPlugin$1;

export { Dialog, DialogCard, DialogPlugin, Dialog as default, dialog };
//# sourceMappingURL=index.js.map
