import Drawer$1 from './Drawer.js';
import './style/css.js';
import '../_chunks/dep-Cwish4GD.js';
import '../_chunks/dep-D-UKOauR.js';
import '../_chunks/dep-DN7d1SzH.js';
import '../_chunks/dep-CzLhKWCf.js';
import 'react';
import 'react-transition-group';
import '@tendaui/icons';
import 'classnames';
import 'lodash-es';
import '../_chunks/dep-aX8qrQpB.js';
import '../button/index.js';
import '../button/Button.js';
import '../_chunks/dep-u7AyxuYF.js';
import '../_chunks/dep-zVwpnryi.js';
import 'dayjs';
import '../loading/index.js';
import '../loading/Loading.js';
import '../_chunks/dep-DRwijJcv.js';
import '../common/Portal.js';
import 'react-dom';
import '../_chunks/dep-BRbJGDI9.js';
import '../loading/Gradient.js';
import '../_chunks/dep-DHWwZ2Nj.js';
import '../_chunks/dep-PPA-yoAy.js';
import '../_chunks/dep-DGvfel3I.js';
import '../_chunks/dep-DbVHGoUC.js';
import '../loading/style/css.js';
import '../_chunks/dep-D6YxJv-F.js';
import '../button/style/css.js';
import '../_chunks/dep-TZtijX-L.js';
import '../_chunks/dep-sSDUpJwy.js';
import './utils/index.js';
import '../_chunks/dep-BGP3l2nd.js';
import '../config-provider/index.js';
import '../config-provider/ConfigProvider.js';

var Drawer = Drawer$1;

export { Drawer, Drawer as default };
//# sourceMappingURL=index.js.map
