import { F as Form$1, u as useWatch } from '../_chunks/dep-CpNU-v8L.js';
import FormList from './FormList.js';
import { u as useForm } from '../_chunks/dep-4LYjB3c6.js';
import { F as FormItem } from '../_chunks/dep-wDcIa4mJ.js';
import './style/css.js';
import '../_chunks/dep-CgyDw_YI.js';
import '../_chunks/dep-CzLhKWCf.js';
import '../_chunks/dep-Cwish4GD.js';
import '../_chunks/dep-D-UKOauR.js';
import 'react';
import 'classnames';
import '../_chunks/dep-u7AyxuYF.js';
import '../_chunks/dep-zVwpnryi.js';
import 'dayjs';
import '../_chunks/dep-U1T8CQY9.js';
import '../_chunks/dep-Do9UdkhS.js';
import 'hoist-non-react-statics';
import './hooks/useInstance.js';
import '../_chunks/dep-DN7d1SzH.js';
import '../_chunks/dep-DUWadCCb.js';
import 'lodash-es';
import './utils/index.js';
import './FormContext.js';
import '../_chunks/dep-DGvfel3I.js';
import '../_chunks/dep-Chz4ZJCb.js';
import '@tendaui/icons';
import '../_chunks/dep-sSDUpJwy.js';
import '../_chunks/dep-CEKYZaLJ.js';
import '../_chunks/dep-D6YxJv-F.js';
import '../_chunks/dep-DHWwZ2Nj.js';
import '../_chunks/dep-CtgX06Xn.js';
import '../common/Check.js';
import '../_chunks/dep-CCaTIa7l.js';
import '../tag-input/TagInput.js';
import '../input/index.js';
import '../input/Input.js';
import '../_chunks/dep-BRbJGDI9.js';
import '../_chunks/dep-DRwijJcv.js';
import '../_chunks/dep-BGP3l2nd.js';
import '../config-provider/index.js';
import '../config-provider/ConfigProvider.js';
import '../input/InputGroup.js';
import '../input/style/css.js';
import '../tag-input/hooks/useTagList.js';
import '../tag/index.js';
import '../tag/Tag.js';
import '../_chunks/dep-zOZQ0R9g.js';
import '../tag/style/css.js';
import '../hooks/useDragSorter.js';
import '../checkbox/CheckboxGroup.js';

var Form = Form$1;
Form.useForm = useForm;
Form.useWatch = useWatch;
Form.FormItem = FormItem;
Form.FormList = FormList;

export { Form, FormItem, FormList, Form as default, useForm, useWatch };
//# sourceMappingURL=index.js.map
