import TagInput$1 from './TagInput.js';
import './style/css.js';
import '../_chunks/dep-Cwish4GD.js';
import '../_chunks/dep-D-UKOauR.js';
import '../_chunks/dep-CzLhKWCf.js';
import 'react';
import '@tendaui/icons';
import 'lodash-es';
import 'classnames';
import '../_chunks/dep-u7AyxuYF.js';
import '../_chunks/dep-zVwpnryi.js';
import 'dayjs';
import '../input/index.js';
import '../input/Input.js';
import '../_chunks/dep-DN7d1SzH.js';
import '../_chunks/dep-BRbJGDI9.js';
import '../_chunks/dep-DRwijJcv.js';
import '../_chunks/dep-CCaTIa7l.js';
import '../_chunks/dep-D6YxJv-F.js';
import '../_chunks/dep-DGvfel3I.js';
import '../_chunks/dep-BGP3l2nd.js';
import '../config-provider/index.js';
import '../config-provider/ConfigProvider.js';
import '../input/InputGroup.js';
import '../input/style/css.js';
import './hooks/useTagList.js';
import '../_chunks/dep-CgyDw_YI.js';
import '../tag/index.js';
import '../tag/Tag.js';
import '../_chunks/dep-zOZQ0R9g.js';
import '../_chunks/dep-U1T8CQY9.js';
import '../_chunks/dep-sSDUpJwy.js';
import '../_chunks/dep-Do9UdkhS.js';
import 'hoist-non-react-statics';
import '../tag/style/css.js';
import '../hooks/useDragSorter.js';

var TagInput = TagInput$1;

export { TagInput, TagInput as default };
//# sourceMappingURL=index.js.map
